### ISSUE TITLE
Single band images?

### ISSUE THREAD

**Issue by nwilliams-kobold** [Eve-ning/glcmbin5#1]
This seems really cool, but it seems to be restricted to 3 band (RGB) images. Is it possible to apply it to single band (greyscale) images?

I can force it by duplicating the band three times, but not super elegant.

**Comment by Eve-ning** [comment]
Hey there Williams, thanks for taking interest in my project :D

I'm working on this on another parent project, so I'll update the `.pyx` here again

You might be inputting an array of shape `(xxx,yyy)` with grayscale, while it allows shapes of `(xxx,yyy,zzz)`, you just need to add another axis on the back

```python
ar = np.ones([300, 200])
ar.shape
>>> (300, 200)
ar = ar[...,np.newaxis]
ar.shape
>>> (300, 200, 1)
glcm = CyGLCM(ar.astype(np.float32),
              radius=GLCM_RADIUS,
              bins=GLCM_BINS,
              step_size=GLCM_STEPSIZE).create_glcm()
```

I assume you compiled from `glcm.pyx` since my `pip` install is slightly broken

I've updated it with newer a newer calculation method and optimizations on `0.1.5`, the following is the changelog

## Major Changes

- Changed GLCM Channel: **Contrast** -> **Homogeneity**
  -  This is because the `FRModel` team observed that there's little variation in **Contrast**, **Homogeneity** has shown to have more spread out data
- Optimized GLCM again with several `Cython` declarations such as `cdef` and return types
- Fix managing `np.nan` values. Previous version didn't detect them correctly as it `NaN` was prematurely coerced to `0`. Thus `isnan` didn't trigger. 0.1.5 fixes it and will skip over windows that contain `NaN`.
- Made dtypes much smaller, as we expect only small radiuses.

**Comment by nwilliams-kobold** [comment]
Thanks! I was working around the `nan` issue too. I am keen to try the new version. I noticed the `pip install glcmbin5` wasn't working. Instead I used:
```
python c_setup.py build_ext --inplace  
pip install .
```

That worked for the old version but doesn't seem to work with the new version. I get an binary incompatibility error when I import:

```
>>> from glcmbin5.glcm import CyGLCM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nickwilliams/Python/glcmbin5-master/glcmbin5/__init__.py", line 1, in <module>
    from glcmbin5.glcm import CyGLCM
  File "glcmbin5/glcm.pyx", line 1, in init glcmbin5.glcm
    """
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by Eve-ning** [comment]
building it is the recommended approach for now unfortunately

let me know if updating NumPy works, it might be tied to the fact that numpy needs to be `>1.20.0`

See: https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

**Comment by nwilliams-kobold** [comment]
That fixed the compatibility error, and it does work well on the expanded dimension single band array. Thanks!

**Comment by Eve-ning** [comment]
Glad it works!
